<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
        <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
        <OutputType>Library</OutputType>
        <RootNamespace>Game</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>GltfModelPBRShader</AssemblyName>
        <Deterministic>true</Deterministic>
        <LangVersion>preview</LangVersion>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
        <Nullable>disable</Nullable>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateDependencyFile>false</GenerateDependencyFile>
        <ErrorReport>prompt</ErrorReport>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DebugType>pdbonly</DebugType>
        <OutputPath>bin\Debug\</OutputPath>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DebugType>none</DebugType>
        <OutputPath>bin\Release\</OutputPath>
    </PropertyGroup>
    <ItemGroup>
        <None Update="modinfo.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Assets\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Assets\Shaders\terrain_equirectangular.vert" />
        <EmbeddedResource Include="Assets\Shaders\terrain_equirectangular.frag" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="*.cs" />
    </ItemGroup>
    <ItemGroup>
      <Reference Include="Engine">
        <HintPath>..\..\SurvivalcraftApi\Engine\bin\Debug\net10.0\Engine.dll</HintPath>
          <Private>false</Private>
      </Reference>
      <Reference Include="EntitySystem">
        <HintPath>..\..\SurvivalcraftApi\EntitySystem\bin\Debug\net10.0\EntitySystem.dll</HintPath>
          <Private>false</Private>
      </Reference>
      <Reference Include="Survivalcraft">
        <HintPath>..\..\SurvivalcraftApi\Survivalcraft\bin\Debug\net10.0\Survivalcraft.dll</HintPath>
          <Private>false</Private>
      </Reference>
      <Reference Include="0Harmony">
        <HintPath>..\..\SurvivalcraftApi\Survivalcraft\bin\Debug\net10.0\0Harmony.dll</HintPath>
          <Private>false</Private>
      </Reference>
      <Reference Include="Silk.NET.OpenGLES">
        <HintPath>..\..\SurvivalcraftApi\Survivalcraft\bin\Debug\net10.0\Silk.NET.OpenGLES.dll</HintPath>
          <Private>false</Private>
      </Reference>
      <Reference Include="Silk.NET.Core">
        <HintPath>..\..\SurvivalcraftApi\Survivalcraft\bin\Debug\net10.0\Silk.NET.Core.dll</HintPath>
          <Private>false</Private>
      </Reference>
    </ItemGroup>
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <PropertyGroup>
            <PathOfScmod>$(TargetDir)..\$(AssemblyName).scmod</PathOfScmod>
        </PropertyGroup>
        <ZipDirectory SourceDirectory="$(TargetDir)" DestinationFile="$(PathOfScmod)" Overwrite="true" />
        <Message Text="The scmod file has been created: $(PathOfScmod)" Importance="high" />
    </Target>
</Project>
